* Split protocol in actual protocol and server implementation
genericptr/pascal-language-server pull request #78
Opened 2023-07-18 12:51 UTC by mvancanneyt

Ryan,

As I wrote some time ago, I split the lspprotocol package so it contains only the actual protocol classes. 
It no longer depends on any functionality of Lazarus itself.

There is now a lspserver package which contains the actual server implementation. 
This package has a dependency on Lazarus, obviously.

This step was necessary to be able to create a lspclient package which has no dependencies on the Lazarus IDE, allowing to write a LSP client. 

I tested the changed version in VSCode and all works well.

I have already started the lspclient package, but that will be part of a separate pull request.

2023-07-18 14:22 UTC, genericptr commented
scanning over this the only thing I saw that jumped out at me was the code actions seem to be missing. In both files I don't see the original code so did it get lost?

2023-07-18 14:33 UTC, mvancanneyt commented
There were no code actions server-side ? 
That was implemented client-side in the VSCode plugin.

2023-07-18 14:39 UTC, genericptr commented
I didn't implement any yet but the infrastructure was there if we wanted to. The fact the code actions you did were implemented on the client seems to be something to do with VSCode but in theory they should be on the server like the rest of the functionality.

Did you end up keeping any of those code actions btw? If I ever do any code actions I don't want to duplicate them on all the clients (defeats the purpose of the LSP) so we eventually need to move them to the server do we not?

2023-07-18 14:42 UTC, mvancanneyt commented
Ryan, 

I did not remove anything and I never implemented any specific code actions.
All I did was add a 'Code completion' code action client side, but that did not make any use of the 'CodeAction' message as it exists in the LSP protocol.

The basic message infrastructure is still there, I did not touch it. 
but the "process" method empty since there are are no code actions.

2023-07-18 14:49 UTC, genericptr commented
oh I'm sorry Michael I didn't look at the diff carefully enough! It's still all there. I thought I saw some code got deleted.

2023-07-18 14:53 UTC, mvancanneyt commented
No worries. 
It is always better to check carefully :smile:

2023-07-20 14:02 UTC, genericptr commented
Ok just had a chance to review this more and I had one request. Can you restore the unit copyright header on all the the files you split apart? I think you can just copy and paste the old one, no need to update the names/dates since no code actually changed.

2023-07-20 14:46 UTC, mvancanneyt commented
Done.

2023-07-20 15:01 UTC, genericptr commented on src/serverprotocol/PasLS.ApplyEdit.pas
> +// Copyright 2020 Arjan Adriaanse
Michael, I think we've added Arjan Adriaanse to files he didn't write so we should remove it. I'll make a note on the files which he didn't do, including this one.

2023-07-20 15:01 UTC, genericptr commented on src/serverprotocol/PasLS.CodeAction.pas
> +// Copyright 2020 Arjan Adriaanse
Arjan Adriaanse did not author this file.

2023-07-20 15:01 UTC, genericptr commented on src/serverprotocol/PasLS.Command.CompleteCode.pas
> +// Copyright 2020 Arjan Adriaanse
Arjan Adriaanse did not author this file.

2023-07-20 15:02 UTC, genericptr commented on src/serverprotocol/PasLS.Command.FormatCode.pas
> +// Copyright 2020 Arjan Adriaanse
Arjan Adriaanse did not author this file.

2023-07-20 15:02 UTC, genericptr commented on src/serverprotocol/PasLS.Command.InvertAssignment.pas
> +// Copyright 2020 Arjan Adriaanse
Arjan Adriaanse did not author this file.

2023-07-20 15:02 UTC, genericptr commented on src/serverprotocol/PasLS.Command.RemoveEmptyMethods.pas
> +// Copyright 2020 Arjan Adriaanse
Arjan Adriaanse did not author this file.

2023-07-20 15:02 UTC, genericptr commented on src/serverprotocol/PasLS.Diagnostics.pas
> +// Copyright 2020 Arjan Adriaanse
Arjan Adriaanse did not author this file.

2023-07-20 15:03 UTC, genericptr commented on src/serverprotocol/PasLS.DocumentSymbol.pas
> +// Copyright 2020 Arjan Adriaanse
Arjan Adriaanse did not author this file.

2023-07-20 15:03 UTC, genericptr commented on src/serverprotocol/PasLS.ExecuteCommand.pas
> +// Copyright 2020 Arjan Adriaanse
Arjan Adriaanse did not author this file.

2023-07-20 15:03 UTC, genericptr commented on src/serverprotocol/PasLS.ExecuteCommand.pas
> +// Copyright 2020 Ryan Joseph
Year should be 2022

2023-07-20 15:04 UTC, genericptr commented on src/serverprotocol/PasLS.Formatter.pas
> +// Copyright 2020 Arjan Adriaanse
I think this was your file in 2023 actually?

2023-07-20 15:05 UTC, genericptr commented on src/serverprotocol/PasLS.Hover.pas
> +// Copyright 2020 Arjan Adriaanse
Arjan Adriaanse did not author this file.

2023-07-20 15:05 UTC, genericptr commented on src/serverprotocol/PasLS.InlayHint.pas
> +// Copyright 2020 Arjan Adriaanse
Arjan Adriaanse did not author this file.

2023-07-20 15:05 UTC, genericptr commented on src/serverprotocol/PasLS.InlayHint.pas
> +// Copyright 2020 Ryan Joseph
year should be 2022

2023-07-20 15:05 UTC, genericptr commented on src/serverprotocol/PasLS.RemoveEmptyMethods.pas
> +// Copyright 2020 Arjan Adriaanse
Arjan Adriaanse did not author this file.

2023-07-20 15:06 UTC, genericptr commented on src/serverprotocol/PasLS.SignatureHelp.pas
> +// Copyright 2020 Arjan Adriaanse
Arjan Adriaanse did not author this file.

2023-07-20 15:06 UTC, genericptr commented on src/serverprotocol/PasLS.Workspace.pas
> +// Copyright 2020 Arjan Adriaanse
Arjan Adriaanse did not author this file.

2023-07-20 15:07 UTC, genericptr requested changes
I think you copy and pasted too much :) Sorry to bother you with this but I don't want to get copyright/credits wrong. Thanks Michael.

2023-07-20 17:12 UTC, mvancanneyt commented
Ryan,

I corrected it.

For the future, you have my express permission to change such things yourself if you feel it is important.

Personally, I could not care less about copyright info.

2023-07-25 14:22 UTC, genericptr approved these changes
Good enough for now, thanks Michael. :)

2023-07-25 14:22 UTC, merged